// Major hospitals & clinic chains in Vietnam, offered as suggestions in the
// visit form. The Combobox also allows free entry, and any hospital name
// already used in existing visits is merged into this list at runtime.
export const HOSPITALS: string[] = [
  // TP.HCM
  "BV Đa khoa Tâm Anh TP.HCM",
  "BV Đại học Y Dược TP.HCM (ĐHYD)",
  "BV Quân y 175",
  "BV Chợ Rẫy",
  "BV Nhân dân Gia Định",
  "BV Nhân dân 115",
  "BV Thống Nhất",
  "BV Nguyễn Tri Phương",
  "BV Bình Dân",
  "BV Nhi Đồng 1",
  "BV Nhi Đồng 2",
  "BV Nhi Đồng Thành phố",
  "BV Từ Dũ",
  "BV Hùng Vương",
  "BV Ung Bướu TP.HCM",
  "BV Mắt TP.HCM",
  "BV Tai Mũi Họng TP.HCM",
  "BV Da Liễu TP.HCM",
  "BV Răng Hàm Mặt TP.HCM",
  "BV Truyền máu - Huyết học TP.HCM",
  "BV Bệnh Nhiệt đới TP.HCM",
  "BV Chấn thương Chỉnh hình TP.HCM",
  "Viện Tim TP.HCM",
  "BV Pháp Việt (FV)",
  "BV Vinmec Central Park",
  "BV Gia An 115",
  "BV Hoàn Mỹ Sài Gòn",
  "BV Quốc tế City",
  "BV Xuyên Á",
  // Hà Nội
  "BV Đa khoa Tâm Anh Hà Nội",
  "BV Bạch Mai",
  "BV Hữu nghị Việt Đức",
  "BV Trung ương Quân đội 108",
  "BV Đại học Y Hà Nội",
  "BV K (Ung bướu)",
  "BV Nhi Trung ương",
  "BV Phụ sản Trung ương",
  "BV Phụ sản Hà Nội",
  "BV Xanh Pôn",
  "BV Thanh Nhàn",
  "BV E",
  "BV Hữu Nghị",
  "BV Lão khoa Trung ương",
  "BV Mắt Trung ương",
  "BV Tai Mũi Họng Trung ương",
  "BV Da liễu Trung ương",
  "BV Răng Hàm Mặt Trung ương Hà Nội",
  "BV Nội tiết Trung ương",
  "BV Tim Hà Nội",
  "BV Vinmec Times City",
  "BV Việt Pháp Hà Nội",
  "BV Đa khoa Hồng Ngọc",
  "BV Thu Cúc (TCI)",
  // Miền Trung & khác
  "BV Trung ương Huế",
  "BV Đà Nẵng",
  "BV Phụ sản - Nhi Đà Nẵng",
  "BV Đa khoa Quốc tế Vinmec Đà Nẵng",
  "BV Chợ Rẫy - Phnôm Pênh",
  // Chuỗi phòng khám / xét nghiệm
  "Phòng khám Medlatec",
  "Phòng khám Diag",
  "Phòng khám Victoria Healthcare",
  "Phòng khám CarePlus",
  "Nhà thuốc / Trạm y tế địa phương",
];
