// Curated list of common ICD-10 codes with Vietnamese labels, used as
// suggestions in the diagnosis field. Typing either the code (e.g. "F32")
// or the disease name finds the entry; free entry is always possible.
export interface Icd10Entry {
  code: string;
  label: string;
}

export const ICD10: Icd10Entry[] = [
  // A/B — Bệnh nhiễm trùng & ký sinh trùng
  { code: "A09", label: "Tiêu chảy & viêm dạ dày - ruột do nhiễm trùng" },
  { code: "A15", label: "Lao phổi" },
  { code: "A90", label: "Sốt xuất huyết Dengue" },
  { code: "A91", label: "Sốt xuất huyết Dengue có dấu hiệu cảnh báo" },
  { code: "B01", label: "Thủy đậu" },
  { code: "B02", label: "Zona (giời leo)" },
  { code: "B08.4", label: "Bệnh tay chân miệng" },
  { code: "B15", label: "Viêm gan A cấp" },
  { code: "B16", label: "Viêm gan B cấp" },
  { code: "B18.1", label: "Viêm gan B mạn" },
  { code: "B18.2", label: "Viêm gan C mạn" },
  { code: "B20", label: "Bệnh HIV" },
  { code: "B35", label: "Nấm da" },
  { code: "B86", label: "Ghẻ" },
  // C/D — Ung thư & khối u
  { code: "C16", label: "Ung thư dạ dày" },
  { code: "C18", label: "Ung thư đại tràng" },
  { code: "C20", label: "Ung thư trực tràng" },
  { code: "C22", label: "Ung thư gan" },
  { code: "C34", label: "Ung thư phổi" },
  { code: "C50", label: "Ung thư vú" },
  { code: "C53", label: "Ung thư cổ tử cung" },
  { code: "C61", label: "Ung thư tuyến tiền liệt" },
  { code: "C73", label: "Ung thư tuyến giáp" },
  { code: "D06", label: "Tổn thương tiền ung thư cổ tử cung (CIN)" },
  { code: "D24", label: "U lành tuyến vú" },
  { code: "D25", label: "U xơ tử cung" },
  { code: "D34", label: "U lành tuyến giáp" },
  // D5–D8 — Máu
  { code: "D50", label: "Thiếu máu thiếu sắt" },
  { code: "D56", label: "Thalassemia (tan máu bẩm sinh)" },
  { code: "D69.6", label: "Giảm tiểu cầu" },
  // E — Nội tiết, dinh dưỡng, chuyển hóa
  { code: "E03", label: "Suy giáp" },
  { code: "E04", label: "Bướu giáp không độc (bướu cổ)" },
  { code: "E05", label: "Cường giáp (Basedow)" },
  { code: "E06.3", label: "Viêm giáp Hashimoto" },
  { code: "E10", label: "Đái tháo đường típ 1" },
  { code: "E11", label: "Đái tháo đường típ 2" },
  { code: "E14", label: "Đái tháo đường không xác định típ" },
  { code: "E66", label: "Béo phì" },
  { code: "E78.0", label: "Tăng cholesterol máu" },
  { code: "E78.5", label: "Rối loạn lipid máu (mỡ máu)" },
  { code: "E79.0", label: "Tăng acid uric máu" },
  { code: "E86", label: "Mất nước" },
  // F — Rối loạn tâm thần & hành vi
  { code: "F20", label: "Tâm thần phân liệt" },
  { code: "F31", label: "Rối loạn lưỡng cực" },
  { code: "F32", label: "Giai đoạn trầm cảm" },
  { code: "F33", label: "Rối loạn trầm cảm tái diễn" },
  { code: "F41.0", label: "Rối loạn hoảng sợ" },
  { code: "F41.1", label: "Rối loạn lo âu lan tỏa" },
  { code: "F41.2", label: "Rối loạn hỗn hợp lo âu - trầm cảm" },
  { code: "F42", label: "Rối loạn ám ảnh cưỡng chế (OCD)" },
  { code: "F43.1", label: "Rối loạn stress sau sang chấn (PTSD)" },
  { code: "F45", label: "Rối loạn dạng cơ thể" },
  { code: "F51.0", label: "Mất ngủ không thực tổn" },
  { code: "F80", label: "Rối loạn phát triển ngôn ngữ" },
  { code: "F84.0", label: "Tự kỷ" },
  { code: "F90", label: "Tăng động giảm chú ý (ADHD)" },
  // G — Thần kinh
  { code: "G40", label: "Động kinh" },
  { code: "G43", label: "Đau nửa đầu (Migraine)" },
  { code: "G44", label: "Hội chứng đau đầu khác" },
  { code: "G45", label: "Cơn thiếu máu não thoáng qua (TIA)" },
  { code: "G47.0", label: "Mất ngủ" },
  { code: "G51.0", label: "Liệt mặt (liệt Bell)" },
  { code: "G54", label: "Bệnh rễ thần kinh" },
  { code: "G56.0", label: "Hội chứng ống cổ tay" },
  { code: "G62.9", label: "Bệnh đa dây thần kinh" },
  { code: "G20", label: "Bệnh Parkinson" },
  { code: "G30", label: "Bệnh Alzheimer" },
  // H00–H59 — Mắt
  { code: "H00", label: "Chắp / lẹo mắt" },
  { code: "H10", label: "Viêm kết mạc (đau mắt đỏ)" },
  { code: "H25", label: "Đục thủy tinh thể tuổi già" },
  { code: "H40", label: "Glôcôm (cườm nước)" },
  { code: "H52.1", label: "Cận thị" },
  { code: "H52.2", label: "Loạn thị" },
  { code: "H52.4", label: "Lão thị" },
  { code: "H04.4", label: "Viêm tắc lệ đạo" },
  // H60–H95 — Tai
  { code: "H60", label: "Viêm ống tai ngoài" },
  { code: "H65", label: "Viêm tai giữa không mủ" },
  { code: "H66", label: "Viêm tai giữa mủ" },
  { code: "H81.1", label: "Chóng mặt tư thế kịch phát lành tính (BPPV)" },
  { code: "H90", label: "Nghe kém" },
  { code: "H93.1", label: "Ù tai" },
  // I — Tuần hoàn
  { code: "I10", label: "Tăng huyết áp vô căn" },
  { code: "I11", label: "Bệnh tim do tăng huyết áp" },
  { code: "I20", label: "Cơn đau thắt ngực" },
  { code: "I21", label: "Nhồi máu cơ tim cấp" },
  { code: "I25", label: "Bệnh tim thiếu máu cục bộ mạn" },
  { code: "I48", label: "Rung nhĩ" },
  { code: "I49", label: "Rối loạn nhịp tim khác" },
  { code: "I50", label: "Suy tim" },
  { code: "I63", label: "Nhồi máu não (đột quỵ thiếu máu)" },
  { code: "I64", label: "Đột quỵ không xác định" },
  { code: "I80", label: "Viêm tắc tĩnh mạch" },
  { code: "I83", label: "Giãn tĩnh mạch chi dưới" },
  { code: "I84", label: "Trĩ" },
  // J — Hô hấp
  { code: "J00", label: "Viêm mũi họng cấp (cảm thường)" },
  { code: "J01", label: "Viêm xoang cấp" },
  { code: "J02", label: "Viêm họng cấp" },
  { code: "J03", label: "Viêm amidan cấp" },
  { code: "J04", label: "Viêm thanh quản cấp" },
  { code: "J06.9", label: "Nhiễm khuẩn hô hấp trên cấp" },
  { code: "J09", label: "Cúm" },
  { code: "J18", label: "Viêm phổi" },
  { code: "J20", label: "Viêm phế quản cấp" },
  { code: "J30", label: "Viêm mũi dị ứng" },
  { code: "J32", label: "Viêm xoang mạn" },
  { code: "J35.0", label: "Viêm amidan mạn" },
  { code: "J44", label: "Bệnh phổi tắc nghẽn mạn tính (COPD)" },
  { code: "J45", label: "Hen phế quản (suyễn)" },
  { code: "U07.1", label: "COVID-19" },
  // K — Tiêu hóa
  { code: "K02", label: "Sâu răng" },
  { code: "K04", label: "Viêm tủy răng" },
  { code: "K05", label: "Viêm nướu / nha chu" },
  { code: "K21", label: "Trào ngược dạ dày - thực quản (GERD)" },
  { code: "K25", label: "Loét dạ dày" },
  { code: "K26", label: "Loét tá tràng" },
  { code: "K29", label: "Viêm dạ dày" },
  { code: "K30", label: "Khó tiêu chức năng" },
  { code: "K35", label: "Viêm ruột thừa cấp" },
  { code: "K40", label: "Thoát vị bẹn" },
  { code: "K52", label: "Viêm dạ dày - ruột không nhiễm trùng" },
  { code: "K58", label: "Hội chứng ruột kích thích (IBS)" },
  { code: "K59.0", label: "Táo bón" },
  { code: "K64", label: "Trĩ (mã mới)" },
  { code: "K74", label: "Xơ gan" },
  { code: "K76.0", label: "Gan nhiễm mỡ" },
  { code: "K80", label: "Sỏi mật" },
  { code: "K81", label: "Viêm túi mật" },
  { code: "K85", label: "Viêm tụy cấp" },
  // L — Da
  { code: "L20", label: "Viêm da cơ địa (chàm thể tạng)" },
  { code: "L21", label: "Viêm da tiết bã" },
  { code: "L23", label: "Viêm da tiếp xúc dị ứng" },
  { code: "L29", label: "Ngứa da" },
  { code: "L40", label: "Vảy nến" },
  { code: "L50", label: "Mày đay" },
  { code: "L60.0", label: "Móng quặp" },
  { code: "L70", label: "Mụn trứng cá" },
  { code: "L81", label: "Rối loạn sắc tố da (nám, tàn nhang)" },
  { code: "L02", label: "Áp xe da / nhọt" },
  // M — Cơ xương khớp
  { code: "M05", label: "Viêm khớp dạng thấp" },
  { code: "M10", label: "Gút (gout)" },
  { code: "M15", label: "Thoái hóa đa khớp" },
  { code: "M17", label: "Thoái hóa khớp gối" },
  { code: "M19", label: "Thoái hóa khớp khác" },
  { code: "M25.5", label: "Đau khớp" },
  { code: "M32", label: "Lupus ban đỏ hệ thống" },
  { code: "M41", label: "Vẹo cột sống" },
  { code: "M47", label: "Thoái hóa cột sống" },
  { code: "M50", label: "Thoát vị đĩa đệm cột sống cổ" },
  { code: "M51", label: "Thoát vị đĩa đệm cột sống thắt lưng" },
  { code: "M54.2", label: "Đau cổ gáy" },
  { code: "M54.4", label: "Đau thắt lưng kèm đau thần kinh tọa" },
  { code: "M54.5", label: "Đau thắt lưng" },
  { code: "M62.8", label: "Chuột rút / co cứng cơ" },
  { code: "M65", label: "Viêm bao gân" },
  { code: "M75", label: "Tổn thương khớp vai (viêm quanh khớp vai)" },
  { code: "M77.1", label: "Viêm lồi cầu ngoài (tennis elbow)" },
  { code: "M79.1", label: "Đau cơ" },
  { code: "M81", label: "Loãng xương" },
  // N — Tiết niệu - sinh dục
  { code: "N18", label: "Bệnh thận mạn" },
  { code: "N20", label: "Sỏi thận / sỏi niệu quản" },
  { code: "N23", label: "Cơn đau quặn thận" },
  { code: "N30", label: "Viêm bàng quang" },
  { code: "N39.0", label: "Nhiễm khuẩn đường tiết niệu" },
  { code: "N40", label: "Phì đại tuyến tiền liệt" },
  { code: "N60", label: "U xơ nang tuyến vú lành tính" },
  { code: "N76", label: "Viêm âm đạo / âm hộ" },
  { code: "N80", label: "Lạc nội mạc tử cung" },
  { code: "N91", label: "Rối loạn kinh nguyệt (vô kinh, kinh thưa)" },
  { code: "N92", label: "Rong kinh / cường kinh" },
  { code: "N95.1", label: "Triệu chứng mãn kinh" },
  // O — Thai sản
  { code: "O09", label: "Theo dõi thai kỳ (khám thai)" },
  { code: "O21", label: "Nghén nặng (nôn nhiều khi mang thai)" },
  { code: "O24.4", label: "Đái tháo đường thai kỳ" },
  { code: "O14", label: "Tiền sản giật" },
  { code: "O80", label: "Sinh thường" },
  { code: "O82", label: "Sinh mổ" },
  // P/Q — Sơ sinh & bẩm sinh
  { code: "P59", label: "Vàng da sơ sinh" },
  { code: "Q65", label: "Loạn sản khớp háng bẩm sinh" },
  // R — Triệu chứng
  { code: "R05", label: "Ho" },
  { code: "R07.0", label: "Đau họng" },
  { code: "R10.4", label: "Đau bụng không xác định" },
  { code: "R11", label: "Buồn nôn / nôn" },
  { code: "R42", label: "Chóng mặt / choáng váng" },
  { code: "R50", label: "Sốt không rõ nguyên nhân" },
  { code: "R51", label: "Đau đầu" },
  { code: "R53", label: "Mệt mỏi / suy nhược" },
  { code: "R63.0", label: "Chán ăn" },
  { code: "R73", label: "Tăng đường huyết" },
  // S/T — Chấn thương
  { code: "S06", label: "Chấn thương sọ não" },
  { code: "S52", label: "Gãy xương cẳng tay" },
  { code: "S62", label: "Gãy xương bàn tay / cổ tay" },
  { code: "S72", label: "Gãy xương đùi" },
  { code: "S82", label: "Gãy xương cẳng chân / mắt cá" },
  { code: "S93.4", label: "Bong gân cổ chân" },
  { code: "T14", label: "Chấn thương không xác định vị trí" },
  { code: "T15", label: "Dị vật ở mắt" },
  { code: "T63", label: "Rắn/côn trùng cắn có nọc độc" },
  { code: "T78.4", label: "Dị ứng không xác định" },
  { code: "T30", label: "Bỏng" },
  // Z — Khám & theo dõi
  { code: "Z00.0", label: "Khám sức khỏe tổng quát" },
  { code: "Z00.1", label: "Khám sức khỏe định kỳ trẻ em" },
  { code: "Z01.0", label: "Khám mắt / đo thị lực" },
  { code: "Z01.1", label: "Khám tai / đo thính lực" },
  { code: "Z01.2", label: "Khám răng" },
  { code: "Z23", label: "Tiêm chủng (vắc xin)" },
  { code: "Z30", label: "Tư vấn kế hoạch hóa gia đình" },
  { code: "Z34", label: "Theo dõi thai bình thường" },
  { code: "Z51.1", label: "Hóa trị ung thư" },
  { code: "Z51.5", label: "Chăm sóc giảm nhẹ" },
];
