// Medical specialties (chuyên khoa) offered in the visit form.
// The Combobox also allows free entry for anything not listed.
export const SPECIALTIES: string[] = [
  "Đa khoa / Khám tổng quát",
  "Nội tổng quát",
  "Tim mạch",
  "Nội tiết - Đái tháo đường",
  "Tiêu hóa - Gan mật",
  "Hô hấp",
  "Thận - Tiết niệu",
  "Cơ xương khớp",
  "Thần kinh",
  "Đột quỵ",
  "Huyết học",
  "Truyền nhiễm",
  "Dị ứng - Miễn dịch",
  "Ung bướu",
  "Nhi khoa",
  "Sơ sinh",
  "Sản phụ khoa",
  "Hiếm muộn - IVF",
  "Nam khoa",
  "Ngoại tổng quát",
  "Chấn thương chỉnh hình",
  "Ngoại thần kinh",
  "Ngoại lồng ngực - Mạch máu",
  "Tai Mũi Họng",
  "Mắt (Nhãn khoa)",
  "Răng Hàm Mặt",
  "Da liễu",
  "Tâm thần - Tâm lý",
  "Lão khoa",
  "Y học cổ truyền",
  "Phục hồi chức năng - Vật lý trị liệu",
  "Dinh dưỡng",
  "Chẩn đoán hình ảnh",
  "Xét nghiệm",
  "Tiêm chủng - Vắc xin",
  "Cấp cứu",
];
